import type { Proposal } from '../../../types/proposal';

const PREVIEW_ROOF_IMAGE = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAIAAAABCAYAAAD0In+KAAAAFElEQVR42mNkYGD4z8DAwMDAAAAHAAH/iZ2RAAAAAElFTkSuQmCC';

/**
 * Dados demonstrativos usados somente no editor de modelos.
 *
 * O documento é o mesmo do PDF final; estes valores garantem que todas as
 * páginas opcionais tenham conteúdo suficiente para serem visualizadas e
 * configuradas antes de existir uma proposta real.
 */
export function createDesignPdfPreviewProposal(profileLogo?: string | null): Proposal {
  const now = new Date().toISOString();

  return {
    id: 'design-pdf-preview',
    user_id: 'design-pdf-preview-user',
    client_id: 'design-pdf-preview-client',
    code: 'PROP-0001',
    title: 'Proposta de sistema fotovoltaico',
    status: 'draft',
    system_type: 'on_grid',
    consumption_source: 'average',
    history: [980, 1040, 1020, 1100, 1080, 1010, 1060, 1120, 1090, 1030, 1000, 1070],
    estimated_daily_consumption: 35,
    monthly_consumption_kwh: 1050,
    bill_amount: 1250,
    energy_tariff: 1.19,
    battery_capacity_kwh: null,
    usable_battery_capacity_kwh: null,
    backup_power_kw: null,
    autonomy_hours: null,
    essential_loads_description: null,
    roof_type: 'Cerâmico',
    roof_area_m2: 92,
    roof_image_url: PREVIEW_ROOF_IMAGE,
    roof_photo_url: null,
    roof_plan_image_url: null,
    roof_latitude_degrees: -23.55,
    roof_planes_json: null,
    roof_orientation_factor: 0.96,
    effective_performance_ratio: 0.79,
    module_width_m: 1.13,
    module_height_m: 2.28,
    roof_layout_json: null,
    selected_solar_kit_id: 'preview-kit',
    solar_kit_snapshot: {
      id: 'preview-kit',
      name: 'Kit Solar Premium 12,50 kWp',
      supplier: 'Distribuidor Solar',
      system_type: 'on_grid',
      module_brand: 'Módulo Premium',
      module_model: '625 Wp Mono',
      module_power_w: 625,
      module_quantity: 20,
      module_height_m: 2.28,
      module_width_m: 1.13,
      inverter_brand: 'Inversor Premium',
      inverter_model: '12 kW Trifásico',
      inverter_power_kw: 12,
      grid_connection_type: 'triphase',
      grid_voltage_v: 380,
      structure_type: 'Estrutura para telhado cerâmico',
      battery_brand: null,
      battery_model: null,
      battery_capacity_kwh: null,
      usable_battery_capacity_kwh: null,
      battery_quantity: null,
      backup_power_kw: null,
      autonomy_hours: null,
      essential_loads_description: null,
      kit_power_kwp: 12.5,
      cost_price: 28500,
      sale_price: 46500,
    },
    kit_cost: 28500,
    labor_cost: 5200,
    fixed_costs: 1800,
    freight_cost: 1200,
    taxes: 3100,
    commission: 1800,
    other_costs: 600,
    margin_percentage: 30,
    discount_percentage: 0,
    total_cost: 42200,
    gross_price: 60285.71,
    discount_value: 0,
    final_price: 60285.71,
    estimated_profit: 18085.71,
    real_margin_percentage: 30,
    markup_percentage: 42.86,
    flow_step: null,
    flow_state: null,
    flow_version: null,
    flow_completed: false,
    flow_last_saved_at: null,
    pdf_url: null,
    pdf_storage_path: null,
    public_token: null,
    sent_whatsapp_at: null,
    accepted_at: null,
    rejected_at: null,
    created_at: now,
    updated_at: now,
    client: {
      name: 'Cliente Exemplo Ltda',
      document: '00.000.000/0001-00',
      email: 'cliente@exemplo.com.br',
      phone: '(11) 99999-9999',
      cep: '01000-000',
      city: 'São Paulo',
      state: 'SP',
      address: 'Avenida Exemplo',
      number: '100',
      neighborhood: 'Centro',
      complement: null,
    },
    solar: {
      installed_power_kwp: 12.5,
      required_power_kwp: 12.5,
      monthly_consumption_kwh: 1050,
      estimated_monthly_generation_kwh: 1580,
      estimated_annual_generation_kwh: 18960,
      monthly_savings: 1200,
      annual_savings: 14400,
      payback_years: 4.2,
      module_quantity: 20,
      module_power_w: 625,
      inverter_power_kw: 12,
      performance_ratio: 0.79,
      irradiation_kwh_m2_day: 5.15,
      degradation_rate: 0.005,
      tariff_inflation_rate: 0.06,
    } as Proposal['solar'],
    loads: [],
    profile: {
      company_name: 'Sol Amigo PRO',
      logo_url: profileLogo || null,
      seller_name: 'Consultor Solar',
      seller_phone: '(11) 99999-0000',
      seller_email: 'consultor@solamigo.com.br',
      seller_signature_url: null,
      website: 'www.solamigo.com.br',
      company_email: 'contato@solamigo.com.br',
      default_validity_days: 7,
      default_margin_percentage: 30,
    },
  };
}
