import approvedImplementationTimelineImage from './approvedImplementationTimelineImage';

export const implementationTimelineNewImage = approvedImplementationTimelineImage;

export default implementationTimelineNewImage;
